# Generated by Django 3.0.5 on 2020-04-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('judul_movie', models.CharField(max_length=200)),
                ('tahun_movie', models.CharField(max_length=20, null=True)),
                ('gross_movie', models.IntegerField(null=True)),
                ('rating_movie', models.FloatField(null=True)),
                ('meta_movie', models.FloatField(null=True)),
                ('vote_movie', models.IntegerField(null=True)),
                ('rate_movie', models.CharField(max_length=50, null=True)),
                ('durasi_movie', models.CharField(max_length=50, null=True)),
                ('deskripsi_movie', models.TextField(null=True)),
                ('link_movie', models.CharField(max_length=200, null=True)),
                ('poster_movie', models.TextField(null=True)),
                ('dt_movie', models.DateTimeField(null=True)),
            ],
        ),
    ]
