# Generated by Django 3.0.5 on 2020-04-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.IntegerField(primary_key=True, serialize=False)),
                ('name_genre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['name_genre'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id_movie', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title_movie', models.CharField(max_length=200)),
                ('year_movie', models.CharField(max_length=20, null=True)),
                ('gross_movie', models.IntegerField(null=True)),
                ('rating_movie', models.FloatField(null=True)),
                ('meta_movie', models.FloatField(null=True)),
                ('vote_movie', models.IntegerField(null=True)),
                ('rate_movie', models.CharField(max_length=50, null=True)),
                ('duration_movie', models.CharField(max_length=50, null=True)),
                ('description_movie', models.TextField(null=True)),
                ('link_movie', models.CharField(max_length=200, null=True)),
                ('poster_movie', models.TextField(null=True)),
                ('dt_movie', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-year_movie'],
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id_name', models.IntegerField(primary_key=True, serialize=False)),
                ('name_name', models.CharField(max_length=100, null=True)),
                ('dateOfBirth_name', models.DateField(null=True)),
                ('placeOfBirth_name', models.CharField(max_length=500, null=True)),
                ('dateOfDeath_name', models.DateField(null=True)),
                ('placeOfDeath_name', models.CharField(max_length=500, null=True)),
                ('birthName_name', models.CharField(max_length=200, null=True)),
                ('height_name', models.CharField(max_length=20, null=True)),
                ('bio_name', models.TextField(null=True)),
                ('poster_name', models.TextField(null=True)),
                ('link_name', models.TextField(null=True)),
            ],
            options={
                'ordering': ['name_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('id_movie_genre', models.IntegerField(primary_key=True, serialize=False)),
                ('id_genre', models.ForeignKey(db_column='id_genre', on_delete=django.db.models.deletion.CASCADE, to='imdb.Genre')),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Director',
            fields=[
                ('id_movie_director', models.IntegerField(primary_key=True, serialize=False)),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
                ('id_name', models.ForeignKey(db_column='id_name', on_delete=django.db.models.deletion.CASCADE, to='imdb.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cast',
            fields=[
                ('id_movie_cast', models.IntegerField(primary_key=True, serialize=False)),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
                ('id_name', models.ForeignKey(db_column='id_name', on_delete=django.db.models.deletion.CASCADE, to='imdb.Name')),
            ],
        ),
    ]
