# Generated by Django 3.0.5 on 2020-04-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB',
            fields=[
                ('id_movie', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('judul_movie', models.CharField(max_length=200)),
            ],
        ),
    ]
