# Generated by Django 3.0.5 on 2020-04-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_genre', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id_name', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_name', models.CharField(max_length=100, null=True)),
                ('dob_name', models.DateField(null=True)),
                ('pob_name', models.CharField(max_length=500, null=True)),
                ('dod_name', models.DateField(null=True)),
                ('pod_name', models.CharField(max_length=500, null=True)),
                ('birth_name_name', models.CharField(max_length=200, null=True)),
                ('height_name', models.CharField(max_length=20, null=True)),
                ('bio_name', models.TextField(null=True)),
                ('poster_name', models.TextField(null=True)),
                ('link_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('id_movie_genre', models.IntegerField(primary_key=True, serialize=False)),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Genre')),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Director',
            fields=[
                ('id_movie_director', models.IntegerField(primary_key=True, serialize=False)),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cast',
            fields=[
                ('id_movie_cast', models.IntegerField(primary_key=True, serialize=False)),
                ('id_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie')),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.Name')),
            ],
        ),
    ]
