# Generated by Django 3.0.5 on 2020-04-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='deskripsi_movie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='dt_movie',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='durasi_movie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='gross_movie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='link_movie',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='meta_movie',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='poster_movie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='rate_movie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='rating_movie',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='tahun_movie',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='imdb',
            name='vote_movie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='id_movie',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
