# Generated by Django 3.0.5 on 2020-04-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_genre_movie_cast_movie_director_movie_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_cast',
            name='id_movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie'),
        ),
        migrations.AlterField(
            model_name='movie_cast',
            name='id_name',
            field=models.ForeignKey(db_column='id_name', on_delete=django.db.models.deletion.CASCADE, to='imdb.Name'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='id_movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie'),
        ),
        migrations.AlterField(
            model_name='movie_director',
            name='id_name',
            field=models.ForeignKey(db_column='id_name', on_delete=django.db.models.deletion.CASCADE, to='imdb.Name'),
        ),
        migrations.AlterField(
            model_name='movie_genre',
            name='id_genre',
            field=models.ForeignKey(db_column='id_genre', on_delete=django.db.models.deletion.CASCADE, to='imdb.Genre'),
        ),
        migrations.AlterField(
            model_name='movie_genre',
            name='id_movie',
            field=models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='imdb.Movie'),
        ),
    ]
