# Generated by Django 3.0.5 on 2020-04-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_auto_20200418_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IMDB',
            new_name='Movie',
        ),
    ]
